### ISSUE TITLE
Handle Duplicated Property Lines In Same Block

### ISSUE THREAD

**Issue by rwakefield** [rwakefield/css_cleaner#1]
When a property line is duplicated in css it only really cares about the last one read so it should just remove the first one.

**Given**

```css
p {
  color: blue;
  color: orange;
}
```

**Output**
```css
p {
  color: orange;
}
```
