### ISSUE TITLE
Combine Redefined Blocks

### ISSUE THREAD

**Issue by rwakefield** [rwakefield/css_cleaner#2]
In css it is totally legal to put the same block more than once in the same file because it will just count the last one as true. If blocks occur multiple times in the same file they should be combined into one.

**Given**
```css
p {
  color: blue;
}

p {
  font-size: 15px;
}
```

**Output**
```css
p {
  color: blue;
  font-size: 15px;
}
```

**Comment by rwakefield** [comment]
Will need to think about replacing when there is duplication involved

**Given**
```css
p {
  color: blue;
}

p {
  color: red;
}
```

**Output**
```css
 p {
  color: red;
 }
```
